server/server.js
Added a console log for when the server begins listening on port 3000! Also added the routes for the reviews api.
All testing was done through postman
=> Added listener logging, added reviews api

client/src/Components/App.jsx
=> Added Q&A component to App.jsx

server/server.js
YEY! This should have the following endpoints:
https://bit.ly/3nTLBpU
=> Added QA endpoint to server

server/server.js
EXPRESS SERVER IS DONE! I AM FREE FROM MY SHACKLES!
=> Added Interactions API and Cart API

client/src/Components/Questions/AnswerItem.jsx, client/src/Components/Questions/AnswersList.jsx, client/src/Components/Questions/QuestionAndAnswer.jsx, client/src/Components/Questions/QuestionItem.jsx, client/src/Components/Questions/QuestionsList.jsx, server/server.js
@apriljgranzow please review
I just realized that my first PR has not been reviewed so those code will be included
=> Dynamic render questions list

client/src/Components/Questions/AnswerItem.jsx, client/src/Components/Questions/AnswersList.jsx, client/src/Components/Questions/QuestionItem.jsx, client/src/Components/Questions/QuestionsList.jsx
=> MVP for helpfulness count for individual answers

client/src/Components/Questions/AnswerItem.jsx, client/src/Components/Questions/AnswersList.jsx, client/src/Components/Questions/QuestionItem.jsx, client/src/Components/Questions/QuestionsList.jsx
=> Helpfulness feature and report feature with disabling

client/src/Components/Questions/AnswerItem.jsx, client/src/Components/Questions/AnswersList.jsx, client/src/Components/Questions/QuestionAndAnswer.jsx, client/src/Components/Questions/QuestionItem.jsx, client/src/Components/Questions/QuestionsList.jsx
@apriljgranzow please review
I finished on the main question list component other than adding answer form and adding question form (which are separate features).
=> Question list main

client/src/Components/Questions/QuestionAndAnswer.jsx, client/src/Components/Questions/SearchBar.jsx, dist/index.html
=> Search bar and function

client/src/Components/Review/Breakdown.jsx, client/src/Components/Review/RatingBreakdown.jsx, client/src/Components/Review/ReviewList.jsx, client/src/Components/Review/ReviewTile.jsx, client/src/Components/Review/Reviews.jsx, client/src/Components/Review/sampleMetadata.js
=> MVP Rating Breakdown component with percentages of each rating

package-lock.json, package.json
=> installed formik

client/src/Components/App.jsx, client/src/Components/Related Products/AddOutfit.jsx, client/src/Components/Related Products/Outfit.jsx, client/src/Components/Related Products/OutfitList.jsx, client/src/Components/Related Products/RelatedProduct.jsx, client/src/Components/Related Products/RelatedProductsList.jsx, dist/Related-Product.css, dist/index.html
Wow what a pain,
I know this is a big pr, feel free to ask questions or come bother me if you don't understand something!
=> Outfit list

client/src/Components/Questions/AddAnswerForm.jsx, client/src/Components/Questions/AddQuestionForm.jsx, client/src/Components/Questions/TextInput.jsx, package-lock.json, package.json
Excluding the submit handler
@apriljgranzow please review
=> Add Question Form

Stylesheet.css, client/src/Components/App.jsx, client/src/Components/Review/RatingBreakdown.jsx, client/src/Components/Review/StackedBar.jsx, dist/styles.css, package-lock.json, package.json, spec/Reviews.test.js
=> Implemented Stacked Bar component

client/src/Components/Review/RatingBreakdown.jsx, client/src/Components/Review/ReviewTile.jsx, client/src/Components/Star.jsx, dist/index.html
=> Star component

client/src/Components/Related Products/Outfit.jsx, client/src/Components/Related Products/RelatedProduct.jsx, dist/Related-Product.css
=> Added star component

dist/reviewStyles.css
=> Added star component styles to reviewStyles.css

client/src/Components/Questions/AddAnswerForm.jsx, client/src/Components/Questions/AddQuestionForm.jsx, client/src/Components/Questions/AnswerItem.jsx, client/src/Components/Questions/AnswersList.jsx, client/src/Components/Questions/QuestionItem.jsx, client/src/Components/Questions/QuestionsList.jsx, dist/questionsStyle.css
=> Question styling

spec/QuestionAndAnswer.test.js
=> Rendering tests for Q&A

client/src/Components/Review/Breakdown.jsx, client/src/Components/Review/RatingBreakdown.jsx, client/src/Components/Review/ReviewForm.jsx, client/src/Components/Review/ReviewList.jsx, client/src/Components/Review/ReviewTile.jsx, dist/reviewStyles.css
=> Final styling changes
